export const BANNED_WORDS = [
  'should',
  'recommend',
  'best',
  'optimal',
  'ideal',
  'smart',
  'unlock',
  'insights',
  'journey',
  'seamless',
  'empower',
  'personalised',
  'personalized',
  'nudge',
  'stay invested',
  'dont miss',
  "don't miss",
  'mistake',
  'regret',
  'panic',
  'guilt',
];

export const COPY = {
  header: {
    title: 'Independent check',
    disclosure: 'Not part of Sampada. We earn nothing whichever option you choose.',
    openedFromAlert: 'Opened from a drawdown alert',
    openedFromRequest: 'Opened from your Pause request',
  },
  c1Entry: {
    title: 'Before you change your SIP',
    subtitle: 'This takes about 45 seconds. You can leave anytime.',
    btnShowChanges: 'Show me what changes',
    btnSkip: "Skip, I've decided",
  },
  c2Reason: {
    title: 'Why are you changing your SIP?',
    subtitle: 'This helps adjust your comparison view.',
    reasons: [
      { id: 'tight', label: 'Money is tight right now', fastPath: true },
      { id: 'scary', label: 'The market looks scary', fastPath: false },
      { id: 'underperforming', label: "This fund isn't performing", fastPath: false },
      { id: 'goal_changed', label: 'My goal has changed', fastPath: false },
      { id: 'other', label: 'Other', fastPath: true },
    ],
    durationLabel: 'For how long?',
    durations: [
      { months: 1, label: '1 month' },
      { months: 3, label: '3 months' },
      { months: 6, label: '6 months' },
      { months: 0, label: 'Not sure' },
    ],
    btnContinue: 'Continue',
  },
  c3Replay: {
    title: 'Your SIP through a past fall',
    subtitle: 'Drag the scrubber to inspect how your monthly investment held up in 2020.',
    keptInvestingLegend: 'Kept investing',
    pausedLegend: 'Paused for 3 months',
    caption: 'This is what happened in one past period. It is not a forecast.',
    negligibleGapText: 'In this period, pausing made little difference.',
    btnNext: 'See current options',
  },
  c4Options: {
    title: 'Your options right now',
    sliderTitle: 'What matters most right now?',
    sliderLeftLabel: 'Reaching my goal',
    sliderRightLabel: 'Breathing room each month',
    leadsMarkerText: 'Leads at this weighting',
    regimeBarLabel: 'Regime boundary',
    receiptTitle: 'Pause receipt',
    skippedRowLabel: 'Skipped contributions',
    growthRowLabel: 'Growth at goal date',
    differenceRowLabel: 'Difference at goal date',
    progressBeforeLabel: 'Goal progress before',
    progressAfterLabel: 'Goal progress after',
    linkStop: 'I want to stop this SIP',
    btnConfirmChoice: 'Select this option',
    assumptionsLink: 'Assumptions & basis',
  },
  c5Confirm: {
    title: 'Review your selection',
    chosenPrefix: 'You chose:',
    reminderLabel: 'Remind me to review in 3 months',
    btnSubmit: 'Make this change in Sampada',
    returnMessage: 'Your SIP instruction has been updated in Sampada.',
  },
  f1FastPath: {
    title: 'Quick consequence check',
    subtitle: 'Impact on your goal progress:',
    btnContinueFull: 'Keep SIP at ₹5,000/mo (90% goal progress)',
    btnReduce: 'Reduce to ₹2,500/mo (60% goal progress)',
    btnPause: 'Pause 3 months (87% goal progress)',
    btnStop: 'Stop SIP (29% goal progress)',
    matterOfFactPause: 'Pausing for 3 months lowers goal progress from 90% to 87%.',
  },
  stopConsequence: {
    title: 'If you stop this SIP',
    body: 'Stopping contributions will leave your goal at 29% progress at your goal date.',
    btnGoBack: 'Go back',
    btnProceedStop: 'Continue to Sampada to stop',
  },
  assumptions: {
    title: 'Assumptions and basis',
    projectionBasis: 'Based on your inputs and an assumed return of 8% a year (range 6% to 10%).',
    skippedMoneyNote: 'Skipped contributions during a pause are assumed to remain uninvested.',
    annualReturnLabel: 'Assumed annual return:',
    goalMonthsLabel: 'Goal timeframe (months):',
    btnClose: 'Close',
  },
  hostApp: {
    brand: 'Sampada',
    subtitle: 'Wealth Management',
    portfolioTitle: 'Investments',
    portfolioValue: '₹4,85,000',
    sipTitle: 'Active SIPs',
    fundName: 'HDFC Mid-Cap Opportunities Fund - Direct - Growth',
    goalLabel: 'Goal: Down payment, ₹6 lakh',
    sipAmount: '₹5,000 / month',
    drawdownBannerText: 'HDFC Mid-Cap Opportunities Fund is 14% below its 12-month peak.',
    btnReviewSip: 'Review your SIP',
    menuPause: 'Pause SIP',
    menuReduce: 'Reduce SIP',
    menuCancel: 'Cancel SIP',
    statusActive: 'Active',
    statusPaused: 'Paused until June 2025',
    statusReduced: 'Reduced to ₹2,500/mo',
  },
  judgePanel: {
    title: 'Judge configuration panel',
    personaLabel: 'Persona',
    asOfDateLabel: 'As of date',
    fundLabel: 'Demo mutual fund',
    returnLabel: 'Assumed return',
    pauseLengthLabel: 'Pause duration',
    btnReset: 'Reset all',
  },
  metricsTab: {
    title: 'Metrics & Guardrails',
    subtext: 'Simulated sessions for demonstration. Not real user data.',
    northStarTitle: 'Informed Decision Rate',
    northStarSub: 'Share of completed checks with >=2 cards viewed, >=15s spent, and an active choice.',
    guardrailsTitle: 'Guardrails & Metrics',
    fastForwardBtn: 'Fast-forward 30 days',
    fastForwardModalTitle: '30-Day Follow-up Survey',
    fastForwardQuestion: 'Would you make the same choice today?',
    btnYes: 'Yes',
    btnNo: 'No',
    btnNotSure: 'Not sure',
  },
  aiAssistant: {
    title: 'Co-pilot Assistant',
    subtitle: 'Decision & application guide',
    disclosure: 'Offline decision assistant. Provides objective explanations, never advice.',
    placeholder: 'Ask a question about your SIP decision or this tool...',
    btnSend: 'Send',
    initialMessage: 'Welcome. Ask any question about how the SIP Pause check works, how calculations are made, or what each option means for your goal.',
  },
};
